"""
=========================================================
Secure-Doc-AI
AI Explanation Layer

Purpose:
This module converts the structured output generated by
the Risk Engine into a human-readable AI underwriting report.
It does NOT modify the Risk Engine output.
It only explains the results.
Works completely offline.
=========================================================
"""

import json
from pathlib import Path

try:
    from evidence_analyzer import analyze_evidence
except ImportError:  # pragma: no cover
    from AI_Explanation.evidence_analyzer import analyze_evidence

try:
    from templates import (
        LOW_RISK_SUMMARY,
        LOW_RISK_EXPLANATION,
        LOW_RISK_RECOMMENDATION,

        MEDIUM_RISK_SUMMARY,
        MEDIUM_RISK_EXPLANATION,
        MEDIUM_RISK_RECOMMENDATION,

        HIGH_RISK_SUMMARY,
        HIGH_RISK_EXPLANATION,
        HIGH_RISK_RECOMMENDATION,

        LOW_DESCRIPTION,
        MEDIUM_DESCRIPTION,
        HIGH_DESCRIPTION,

        LOW_NEXT_STEPS,
        MEDIUM_NEXT_STEPS,
        HIGH_NEXT_STEPS,

        LOW_CONFIDENCE,
        MEDIUM_CONFIDENCE,
        HIGH_CONFIDENCE,

        NAME_PASS,
        NAME_FAIL,

        UNKNOWN_RISK_SUMMARY,
        UNKNOWN_RISK_EXPLANATION,
        UNKNOWN_RISK_RECOMMENDATION
    )
except ImportError:  # pragma: no cover
    from AI_Explanation.templates import (
        LOW_RISK_SUMMARY,
        LOW_RISK_EXPLANATION,
        LOW_RISK_RECOMMENDATION,

        MEDIUM_RISK_SUMMARY,
        MEDIUM_RISK_EXPLANATION,
        MEDIUM_RISK_RECOMMENDATION,

        HIGH_RISK_SUMMARY,
        HIGH_RISK_EXPLANATION,
        HIGH_RISK_RECOMMENDATION,

        LOW_DESCRIPTION,
        MEDIUM_DESCRIPTION,
        HIGH_DESCRIPTION,

        LOW_NEXT_STEPS,
        MEDIUM_NEXT_STEPS,
        HIGH_NEXT_STEPS,

        LOW_CONFIDENCE,
        MEDIUM_CONFIDENCE,
        HIGH_CONFIDENCE,

        NAME_PASS,
        NAME_FAIL,

        UNKNOWN_RISK_SUMMARY,
        UNKNOWN_RISK_EXPLANATION,
        UNKNOWN_RISK_RECOMMENDATION
    )

try:
    from reasoning_engine import perform_reasoning
    from recommendation_engine import generate_recommendation
    from report_builder import build_report, generate_json_report
except ImportError:  # pragma: no cover
    from AI_Explanation.reasoning_engine import perform_reasoning
    from AI_Explanation.recommendation_engine import generate_recommendation
    from AI_Explanation.report_builder import build_report, generate_json_report


# ==========================================================
# Generate AI Explanation
# ==========================================================

def generate_ai_explanation(risk_report):
    """
    Generate AI explanation from Risk Engine output.

    This method now wires together the reasoning engine,
    recommendation engine, and report builder so the full
    underwriting flow is exercised end to end.
    """

    decision = str(risk_report.get("decision", "")).upper()
    name_validation = risk_report.get("name_validation", "")
    reasons = risk_report.get("reasons", [])
    documents = risk_report.get("documents", 0)
    risk_score = risk_report.get("risk_score", 0)
    application_id = risk_report.get("application_id", "unknown")

    # ------------------------------------------------------
    # Select explanation based on risk level
    # ------------------------------------------------------

    if decision == "LOW RISK":
        summary = LOW_RISK_SUMMARY
        explanation = LOW_RISK_EXPLANATION
        recommendation_text = LOW_RISK_RECOMMENDATION
        confidence = LOW_CONFIDENCE
        description = LOW_DESCRIPTION
        next_steps = LOW_NEXT_STEPS
    elif decision == "MEDIUM RISK":
        summary = MEDIUM_RISK_SUMMARY
        explanation = MEDIUM_RISK_EXPLANATION
        recommendation_text = MEDIUM_RISK_RECOMMENDATION
        confidence = MEDIUM_CONFIDENCE
        description = MEDIUM_DESCRIPTION
        next_steps = MEDIUM_NEXT_STEPS
    elif decision == "HIGH RISK":
        summary = HIGH_RISK_SUMMARY
        explanation = HIGH_RISK_EXPLANATION
        recommendation_text = HIGH_RISK_RECOMMENDATION
        confidence = HIGH_CONFIDENCE
        description = HIGH_DESCRIPTION
        next_steps = HIGH_NEXT_STEPS
    else:
        summary = UNKNOWN_RISK_SUMMARY
        explanation = UNKNOWN_RISK_EXPLANATION
        recommendation_text = UNKNOWN_RISK_RECOMMENDATION
        confidence = "Unknown"
        description = "Unknown"
        next_steps = []

    # ------------------------------------------------------
    # Name Validation
    # ------------------------------------------------------

    if str(name_validation).upper() == "PASS":
        identity_message = NAME_PASS
    else:
        identity_message = NAME_FAIL

    # ------------------------------------------------------
    # Build rich reasoning and recommendation output
    # ------------------------------------------------------

    evidence_analysis = analyze_evidence(reasons)
    evidence = evidence_analysis.get("evidence", reasons)
    reasoning = perform_reasoning(evidence)
    recommendation = generate_recommendation(evidence)
    report = build_report(
        application_id=application_id,
        evidence=evidence,
        documents_analyzed=documents,
        risk_score=risk_score,
        decision=decision,
        name_validation=name_validation,
    )

    ai_report = {
        "application_id": application_id,
        "documents_analyzed": documents,
        "risk_score": risk_score,
        "decision": decision,
        "risk_level_description": description,
        "summary": summary,
        "risk_explanation": explanation,
        "identity_validation": identity_message,
        "detected_issues": reasons,
        "confidence": confidence,
        "recommendation": recommendation_text,
        "next_steps": next_steps,
        "reasoning": reasoning,
        "evidence_analysis": evidence_analysis,
        "recommendation_engine": recommendation,
        "report": report,
        "text_report": report.get("text_summary", ""),
        "report_json": generate_json_report(report),
    }

    return ai_report


# ==========================================================
# Read Risk Report JSON
# ==========================================================

def load_risk_report(file_path):
    """
    Reads Risk Engine JSON file.
    """

    with open(file_path, "r") as file:
        return json.load(file)


# ==========================================================
# Save AI Explanation
# ==========================================================

def save_ai_report(ai_report, output_path):
    """
    Saves AI report as JSON.
    """

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as file:
        json.dump(ai_report, file, indent=4)


def get_demo_test_cases():
    return [
        {
            "application_id": "genuine_001",
            "documents": 3,
            "name_validation": "PASS",
            "risk_score": 5,
            "decision": "LOW RISK",
            "reasons": ["No suspicious activity detected"],
        },
        {
            "application_id": "salary_tampered_001",
            "documents": 3,
            "name_validation": "FAIL",
            "risk_score": 185,
            "decision": "HIGH RISK",
            "reasons": [
                "High forgery score in salary_slip",
                "Tampering detected in salary_slip",
            ],
        },
        {
            "application_id": "name_mismatch_001",
            "documents": 3,
            "name_validation": "FAIL",
            "risk_score": 120,
            "decision": "MEDIUM RISK",
            "reasons": ["Name mismatch across documents"],
        },
        {
            "application_id": "bank_tampered_001",
            "documents": 3,
            "name_validation": "FAIL",
            "risk_score": 190,
            "decision": "HIGH RISK",
            "reasons": [
                "High forgery score in bank_statement",
                "Tampering detected in bank_statement",
            ],
        },
        {
            "application_id": "property_tampered_001",
            "documents": 3,
            "name_validation": "FAIL",
            "risk_score": 200,
            "decision": "HIGH RISK",
            "reasons": [
                "High forgery score in property_document",
                "Tampering detected in property_document",
            ],
        },
        {
            "application_id": "all_tampered_001",
            "documents": 3,
            "name_validation": "FAIL",
            "risk_score": 250,
            "decision": "HIGH RISK",
            "reasons": [
                "High forgery score in salary_slip",
                "Tampering detected in salary_slip",
                "High forgery score in bank_statement",
                "Tampering detected in bank_statement",
                "High forgery score in property_document",
                "Tampering detected in property_document",
                "Name mismatch across documents",
            ],
        },
    ]


def generate_demo_reports(output_path=None):
    output_path = output_path or Path(__file__).resolve().parent.parent / "reports" / "ai_underwriting_report.json"
    output_path = Path(output_path)
    reports = [generate_ai_explanation(payload) for payload in get_demo_test_cases()]
    save_ai_report(reports, output_path)
    return output_path


# ==========================================================
# Example Execution
# ==========================================================

if __name__ == "__main__":

    INPUT_FILE = "../Risk_Engine/reports/risk_report.json"

    OUTPUT_FILE = "../reports/ai_underwriting_report.json"

    risk_data = load_risk_report(INPUT_FILE)

    # Handle both:
    # 1. Single JSON object
    # 2. List of applications

    if isinstance(risk_data, list):

        reports = []

        for report in risk_data:
            reports.append(generate_ai_explanation(report))

        save_ai_report(reports, OUTPUT_FILE)

        print(f"{len(reports)} AI reports generated successfully.")

    else:

        report = generate_ai_explanation(risk_data)

        save_ai_report(report, OUTPUT_FILE)

        print("AI report generated successfully.")