"""
=========================================================
Secure-Doc-AI
Reasoning Engine
Purpose
This module performs Explainable AI reasoning over the
structured evidence generated by evidence_analyzer.py.
It DOES NOT make the underwriting decision.
The Risk Engine already does that.
Its responsibility is to explain WHY the decision
was taken using structured evidence.
=========================================================
"""

from collections import Counter
from statistics import mean

try:
    from evidence_analyzer import build_evidence as _build_evidence
except ImportError:  # pragma: no cover - fallback for direct execution
    _build_evidence = None


# =====================================================
# Priority Tables
# =====================================================

SEVERITY_PRIORITY = {
    "Critical": 4,
    "High": 3,
    "Medium": 2,
    "Low": 1,
}


CATEGORY_PRIORITY = {
    "Forgery Detection": 5,
    "Document Tampering": 5,
    "Identity Verification": 4,
    "Cross Document Validation": 4,
    "Metadata Analysis": 3,
    "General Verification": 2,
}


# =====================================================
# Utility Functions
# =====================================================

def _drop_empty_reason(reason):
    if not reason:
        return ""
    return str(reason).strip()


def _infer_document(reason):
    text = _drop_empty_reason(reason).lower()
    if "salary" in text:
        return "Salary Slip"
    if "bank" in text:
        return "Bank Statement"
    if "property" in text:
        return "Property Document"
    return "Unknown Document"


def _infer_category(reason):
    text = _drop_empty_reason(reason).lower()
    if "forgery" in text:
        return "Forgery Detection"
    if "tampering" in text:
        return "Document Tampering"
    if "metadata" in text:
        return "Metadata Analysis"
    if "mismatch" in text:
        return "Cross Document Validation"
    if "name" in text or "identity" in text:
        return "Identity Verification"
    return "General Verification"


def _infer_severity(reason):
    text = _drop_empty_reason(reason).lower()
    if "tampering" in text or "forgery" in text:
        return "Critical"
    if "metadata" in text or "mismatch" in text:
        return "High"
    if "missing" in text:
        return "Medium"
    return "Low"


def _infer_confidence(reason):
    severity = _infer_severity(reason)
    mapping = {
        "Critical": 98,
        "High": 90,
        "Medium": 75,
        "Low": 60,
    }
    return mapping.get(severity, 50)


def _coerce_evidence_item(item):
    if isinstance(item, dict):
        raw_reason = item.get("raw_reason") or item.get("reason") or item.get("finding") or item.get("description") or ""
        if raw_reason:
            evidence = {
                "raw_reason": _drop_empty_reason(raw_reason),
                "document": item.get("document") or _infer_document(raw_reason),
                "category": item.get("category") or _infer_category(raw_reason),
                "severity": item.get("severity") or _infer_severity(raw_reason),
                "confidence": item.get("confidence") or _infer_confidence(raw_reason),
            }
            evidence.update(item)
            evidence["raw_reason"] = _drop_empty_reason(evidence.get("raw_reason", ""))
            return evidence

        return {
            "raw_reason": "",
            "document": item.get("document") or "Unknown Document",
            "category": item.get("category") or "General Verification",
            "severity": item.get("severity") or "Low",
            "confidence": item.get("confidence") or 60,
        }

    if isinstance(item, str):
        reason = _drop_empty_reason(item)
        if _build_evidence is not None:
            try:
                evidence = _build_evidence(reason)
                return evidence
            except Exception:
                pass
        return {
            "raw_reason": reason,
            "document": _infer_document(reason),
            "category": _infer_category(reason),
            "severity": _infer_severity(reason),
            "confidence": _infer_confidence(reason),
        }

    return {
        "raw_reason": "",
        "document": "Unknown Document",
        "category": "General Verification",
        "severity": "Low",
        "confidence": 60,
    }


def normalize_evidence(evidence):
    if evidence is None:
        return []

    if isinstance(evidence, dict):
        if isinstance(evidence.get("evidence"), list):
            evidence = evidence["evidence"]
        elif isinstance(evidence.get("reasons"), list):
            evidence = evidence["reasons"]
        else:
            evidence = [evidence]

    if isinstance(evidence, (str, bytes)):
        evidence = [evidence]

    if not isinstance(evidence, list):
        return []

    normalized = []
    for item in evidence:
        normalized.append(_coerce_evidence_item(item))

    return normalized


def sort_by_severity(evidence):
    """
    Returns evidence sorted from highest severity.
    """
    normalized = normalize_evidence(evidence)
    return sorted(
        normalized,
        key=lambda x: SEVERITY_PRIORITY.get(x.get("severity"), 0),
        reverse=True,
    )


def highest_severity(evidence):
    normalized = normalize_evidence(evidence)
    if not normalized:
        return "None"
    ranked = sort_by_severity(normalized)
    return ranked[0].get("severity", "Low")


def affected_documents(evidence):
    normalized = normalize_evidence(evidence)
    docs = []
    for item in normalized:
        document = item.get("document", "Unknown Document")
        if document not in docs:
            docs.append(document)
    return docs


def affected_categories(evidence):
    normalized = normalize_evidence(evidence)
    cats = []
    for item in normalized:
        category = item.get("category", "General Verification")
        if category not in cats:
            cats.append(category)
    return cats


# =====================================================
# Risk Pattern Analysis
# =====================================================

def analyse_patterns(evidence):
    """
    Detect recurring fraud patterns.
    """
    normalized = normalize_evidence(evidence)
    patterns = []

    categories = Counter()
    documents = Counter()
    severities = Counter()

    for item in normalized:
        categories[item.get("category", "General Verification")] += 1
        documents[item.get("document", "Unknown Document")] += 1
        severities[item.get("severity", "Low")] += 1

    if categories["Forgery Detection"] > 0:
        patterns.append("Forgery indicators detected.")
    if categories["Document Tampering"] > 0:
        patterns.append("Document tampering evidence identified.")
    if categories["Cross Document Validation"] > 0:
        patterns.append("Cross-document inconsistencies observed.")
    if categories["Identity Verification"] > 0:
        patterns.append("Identity verification failed.")
    if categories["General Verification"] > 0 and not patterns:
        patterns.append("Additional verification may still be required.")

    return {
        "categories": dict(categories),
        "documents": dict(documents),
        "severity": dict(severities),
        "patterns": patterns,
    }


# =====================================================
# Evidence Ranking
# =====================================================

def rank_evidence(evidence):
    """
    Produces ranked evidence.

    Highest priority first.
    """
    normalized = normalize_evidence(evidence)
    ranked = sort_by_severity(normalized)

    result = []
    rank = 1
    for item in ranked:
        result.append({
            "rank": rank,
            "document": item.get("document", "Unknown Document"),
            "category": item.get("category", "General Verification"),
            "severity": item.get("severity", "Low"),
            "confidence": item.get("confidence", 60),
            "finding": item.get("raw_reason", ""),
        })
        rank += 1

    return result


# =====================================================
# Overall Severity
# =====================================================

def overall_severity(evidence):
    normalized = normalize_evidence(evidence)
    if not normalized:
        return "Low"

    values = [SEVERITY_PRIORITY.get(item.get("severity"), 1) for item in normalized]
    avg = mean(values)

    if avg >= 3.5:
        return "Critical"
    if avg >= 2.7:
        return "High"
    if avg >= 1.8:
        return "Medium"
    return "Low"


# =====================================================
# Evidence Quality
# =====================================================

def evidence_quality(evidence):
    """
    Estimates evidence reliability.
    """
    normalized = normalize_evidence(evidence)
    if not normalized:
        return "Insufficient"

    confidence = mean([e.get("confidence", 0) for e in normalized])

    if confidence >= 95:
        return "Very Strong"
    if confidence >= 85:
        return "Strong"
    if confidence >= 70:
        return "Moderate"
    return "Weak"


# =====================================================
# Contradiction Detection
# =====================================================

def detect_contradictions(evidence):
    """
    Detect contradictory findings.
    """
    normalized = normalize_evidence(evidence)
    contradictions = []

    text = " ".join([e.get("raw_reason", "").lower() for e in normalized])

    if "genuine" in text and "forgery" in text:
        contradictions.append("Conflicting authenticity indicators.")
    if "pass" in text and "fail" in text:
        contradictions.append("Identity validation appears inconsistent across the evidence set.")

    return contradictions


# =====================================================
# NEW: Executive Summary Generator
# =====================================================

def generate_executive_summary(evidence, overall_risk=None):
    normalized = normalize_evidence(evidence)
    severity = overall_risk or overall_severity(normalized)
    if not normalized:
        return "The review contains no actionable evidence. The case appears straightforward and low risk."

    if severity == "Critical":
        return "Multiple critical fraud indicators were identified across the submitted documents, pointing to a high likelihood of tampering or fraudulent presentation."
    if severity == "High":
        return "The case contains several significant anomalies that warrant closer underwriting review and possible escalation."
    if severity == "Medium":
        return "The evidence suggests moderate concerns that should be addressed through additional verification."
    return "The evidence is generally consistent and does not indicate material fraud risk at this stage."


# =====================================================
# NEW: Key Findings Generator
# =====================================================

def generate_key_findings(evidence):
    ranked = rank_evidence(evidence)
    findings = []
    for item in ranked[:5]:
        findings.append({
            "finding": item["finding"],
            "severity": item["severity"],
            "document": item["document"],
            "category": item["category"],
        })
    if not findings:
        findings.append({
            "finding": "No material findings were detected.",
            "severity": "Low",
            "document": "Unknown Document",
            "category": "General Verification",
        })
    return findings


# =====================================================
# NEW: Risk Narrative Generator
# =====================================================

def generate_risk_narrative(evidence):
    normalized = normalize_evidence(evidence)
    if not normalized:
        return "No evidence was supplied, so the review remains neutral."

    highest = highest_severity(normalized)
    docs = affected_documents(normalized)
    categories = affected_categories(normalized)
    return (
        f"The review identified {len(normalized)} evidence item(s) with a highest severity of {highest}. "
        f"The concerns span {', '.join(docs) if docs else 'no documents'} and involve {', '.join(categories) if categories else 'no categories'}."
    )


# =====================================================
# NEW: Identity Analysis
# =====================================================

def analyze_identity(evidence):
    normalized = normalize_evidence(evidence)
    issues = []
    for item in normalized:
        reason = item.get("raw_reason", "")
        if any(keyword in reason.lower() for keyword in ["name", "identity", "mismatch", "inconsistent"]):
            issues.append(reason)

    if issues:
        return {
            "status": "FAIL",
            "summary": "Identity inconsistencies were detected across the submitted evidence.",
            "issues": issues,
        }

    return {
        "status": "PASS",
        "summary": "No identity inconsistencies were detected in the supplied evidence.",
        "issues": [],
    }


# =====================================================
# NEW: Document Analysis
# =====================================================

def analyze_documents(evidence):
    normalized = normalize_evidence(evidence)
    document_counts = Counter(item.get("document", "Unknown Document") for item in normalized)
    ranked_documents = sorted(document_counts.items(), key=lambda x: x[1], reverse=True)
    highest_risk_document = ranked_documents[0][0] if ranked_documents else "Unknown Document"

    return {
        "affected_documents": affected_documents(normalized),
        "document_breakdown": dict(document_counts),
        "highest_risk_document": highest_risk_document,
    }


def build_document_wise_analysis(evidence):
    normalized = normalize_evidence(evidence)
    analysis = {}
    for document in affected_documents(normalized):
        doc_items = [item for item in normalized if item.get("document") == document]
        severity_values = [SEVERITY_PRIORITY.get(item.get("severity"), 1) for item in doc_items]
        highest_severity = "Low"
        if max(severity_values, default=1) >= 4:
            highest_severity = "Critical"
        elif max(severity_values, default=1) >= 3:
            highest_severity = "High"
        elif max(severity_values, default=1) >= 2:
            highest_severity = "Medium"

        analysis[document] = {
            "evidence_count": len(doc_items),
            "highest_severity": highest_severity,
            "findings": [item.get("raw_reason", "") for item in doc_items if item.get("raw_reason")],
        }

    return analysis


# =====================================================
# NEW: Fraud Analysis
# =====================================================

def analyze_fraud(evidence):
    normalized = normalize_evidence(evidence)
    signals = []
    tampering_detected = False
    severity_score = 0

    for item in normalized:
        reason = item.get("raw_reason", "")
        if "tampering" in reason.lower():
            tampering_detected = True
            signals.append("Tampering indicators detected.")
        if "forgery" in reason.lower():
            signals.append("Forgery indicators detected.")
        if "mismatch" in reason.lower():
            signals.append("Cross-document mismatch observed.")

        severity_score += SEVERITY_PRIORITY.get(item.get("severity"), 1)

    fraud_probability = min(100, int(round((severity_score / max(1, len(normalized) * 4)) * 100)))
    if fraud_probability < 0:
        fraud_probability = 0

    return {
        "fraud_signals": signals or ["No overt fraud signal was detected."],
        "tampering_detected": tampering_detected,
        "fraud_probability": fraud_probability,
        "risk_level": overall_severity(normalized),
    }


# =====================================================
# NEW: Evidence Strength Analysis
# =====================================================

def analyze_evidence_strength(evidence):
    normalized = normalize_evidence(evidence)
    if not normalized:
        return {
            "quality": "Insufficient",
            "confidence": 0,
            "evidence_count": 0,
            "strength": "Insufficient",
        }

    confidence = round(mean([item.get("confidence", 0) for item in normalized]), 2)
    quality = evidence_quality(normalized)
    strength = "Strong" if quality in ["Very Strong", "Strong"] else "Moderate" if quality == "Moderate" else "Weak"

    return {
        "quality": quality,
        "confidence": confidence,
        "evidence_count": len(normalized),
        "strength": strength,
    }


# =====================================================
# NEW: Decision Justification
# =====================================================

def build_decision_justification(evidence, overall_risk=None):
    severity = overall_risk or overall_severity(evidence)
    ranked = rank_evidence(evidence)[:3]
    evidence_points = [item["finding"] for item in ranked if item["finding"]]

    return {
        "decision": severity,
        "justification": "The decision is driven by the concentration of high-severity fraud signals and inconsistencies in the supporting evidence.",
        "supporting_evidence": evidence_points,
    }


# =====================================================
# NEW: Underwriting Reasoning
# =====================================================

def build_underwriting_reasoning(evidence):
    normalized = normalize_evidence(evidence)
    documents = affected_documents(normalized)
    recommendations = []
    if overall_severity(normalized) in ["High", "Critical"]:
        recommendations.append("Manual review is required before any underwriting decision is finalized.")
        recommendations.append("Verify supporting documentation directly with the issuer.")
    else:
        recommendations.append("Proceed with standard review and monitor for new evidence.")

    return {
        "recommendation": recommendations[0],
        "review_focus": documents,
        "next_steps": recommendations,
    }


# =====================================================
# NEW: AI Confidence Reasoning
# =====================================================

def build_ai_confidence_reasoning(evidence):
    strength = analyze_evidence_strength(evidence)
    contradictions = detect_contradictions(evidence)

    if strength["confidence"] >= 90 and not contradictions:
        confidence_level = "High"
        rationale = "The evidence set is internally consistent and strongly points to the same conclusion."
    elif strength["confidence"] >= 75:
        confidence_level = "Medium"
        rationale = "The evidence is moderately strong, but some findings still require human review."
    else:
        confidence_level = "Low"
        rationale = "The evidence is limited or inconsistent, so the conclusion should be treated cautiously."

    return {
        "confidence": confidence_level,
        "confidence_score": strength["confidence"],
        "reason": rationale,
    }


def build_confidence_explanation(evidence):
    strength = analyze_evidence_strength(evidence)
    confidence_reasoning = build_ai_confidence_reasoning(evidence)
    return {
        "confidence_level": confidence_reasoning["confidence"],
        "confidence_score": strength["confidence"],
        "explanation": confidence_reasoning["reason"],
        "quality": strength["quality"],
    }


# =====================================================
# NEW: Risk Indicators
# =====================================================

def build_risk_indicators(evidence):
    normalized = normalize_evidence(evidence)
    indicators = []
    for item in normalized:
        reason = item.get("raw_reason", "")
        if reason:
            indicators.append(reason)
    if not indicators:
        indicators.append("No material risk indicators were surfaced.")
    return indicators


# =====================================================
# NEW: Business Impact
# =====================================================

def build_business_impact(evidence):
    severity = overall_severity(evidence)
    if severity == "Critical":
        impact_level = "Severe"
        summary = "The case could expose the organization to significant financial loss and reputational damage if it proceeds without intervention."
    elif severity == "High":
        impact_level = "High"
        summary = "The case may lead to operational delays, policy exceptions, and elevated fraud exposure."
    elif severity == "Medium":
        impact_level = "Moderate"
        summary = "The case may require additional oversight and could affect processing efficiency."
    else:
        impact_level = "Low"
        summary = "The case is unlikely to create significant business disruption."

    return {
        "impact_level": impact_level,
        "summary": summary,
        "potential_consequences": [
            "Delayed onboarding or loan approval",
            "Manual review cost",
            "Reputational exposure if fraud is later confirmed",
        ],
    }


# =====================================================
# NEW: Compliance Notes
# =====================================================

def build_compliance_notes(evidence):
    normalized = normalize_evidence(evidence)
    notes = []
    if overall_severity(normalized) in ["High", "Critical"]:
        notes.append("Escalation to the compliance or fraud investigation team is recommended.")
    if analyze_identity(normalized)["status"] == "FAIL":
        notes.append("Identity verification should be independently validated before any approval decision.")
    if not notes:
        notes.append("Normal documentation controls remain sufficient for this case.")
    return notes


# =====================================================
# NEW: Case Complexity
# =====================================================

def assess_case_complexity(evidence):
    normalized = normalize_evidence(evidence)
    count = len(normalized)
    categories = len(set(item.get("category", "General Verification") for item in normalized))
    if count >= 6 or categories >= 3:
        return "High"
    if count >= 3 or categories >= 2:
        return "Medium"
    return "Low"


# =====================================================
# NEW: Escalation Reason
# =====================================================

def determine_escalation_reason(evidence):
    normalized = normalize_evidence(evidence)
    if overall_severity(normalized) == "Critical":
        return "Critical fraud indicators and tampering concerns require immediate senior review."
    if analyze_identity(normalized)["status"] == "FAIL":
        return "Identity inconsistencies require manual verification and escalation."
    if len(normalized) >= 4:
        return "Multiple independent findings justify escalation for a more detailed review."
    return "The case should be reviewed by a qualified analyst for final disposition."


# =====================================================
# NEW: Final Reasoning Object
# =====================================================

def build_final_reasoning_object(evidence, overall_risk=None):
    normalized = normalize_evidence(evidence)
    severity = overall_risk or overall_severity(normalized)
    return {
        "overall_severity": severity,
        "evidence_quality": evidence_quality(normalized),
        "patterns": analyse_patterns(normalized)["patterns"],
        "contradictions": detect_contradictions(normalized),
        "recommended_action": "Manual review required" if severity in ["High", "Critical"] else "Standard review",
    }


# =====================================================
# Evidence Summary
# =====================================================

def summarize_evidence(evidence):
    """
    Creates structured summary.

    Used by report builder.
    """
    normalized = normalize_evidence(evidence)
    patterns = analyse_patterns(normalized)
    overall_risk = overall_severity(normalized)

    summary = {
        "documents": affected_documents(normalized),
        "categories": affected_categories(normalized),
        "overall_severity": overall_risk,
        "evidence_quality": evidence_quality(normalized),
        "patterns": patterns["patterns"],
        "ranked_evidence": rank_evidence(normalized),
        "contradictions": detect_contradictions(normalized),
        "executive_summary": generate_executive_summary(normalized, overall_risk),
        "key_findings": generate_key_findings(normalized),
        "risk_narrative": generate_risk_narrative(normalized),
        "identity_analysis": analyze_identity(normalized),
        "document_analysis": analyze_documents(normalized),
        "document_wise_analysis": build_document_wise_analysis(normalized),
        "fraud_analysis": analyze_fraud(normalized),
        "evidence_strength_analysis": analyze_evidence_strength(normalized),
        "decision_justification": build_decision_justification(normalized, overall_risk),
        "underwriting_reasoning": build_underwriting_reasoning(normalized),
        "ai_confidence_reasoning": build_ai_confidence_reasoning(normalized),
        "confidence_explanation": build_confidence_explanation(normalized),
        "risk_indicators": build_risk_indicators(normalized),
        "business_impact": build_business_impact(normalized),
        "compliance_notes": build_compliance_notes(normalized),
        "case_complexity": assess_case_complexity(normalized),
        "escalation_reason": determine_escalation_reason(normalized),
        "final_reasoning_object": build_final_reasoning_object(normalized, overall_risk),
    }

    return summary


# =====================================================
# Main Reasoning API
# =====================================================

def perform_reasoning(evidence):
    """
    Main function called by explanation.py
    """
    summary = summarize_evidence(evidence)
    return summary


# =====================================================
# Testing
# =====================================================

if __name__ == "__main__":

    sample = [

        {

            "raw_reason":

                "High forgery score in salary_slip",

            "document":

                "Salary Slip",

            "category":

                "Forgery Detection",

            "severity":

                "Critical",

            "confidence":

                98

        },

        {

            "raw_reason":

                "Tampering detected in salary_slip",

            "document":

                "Salary Slip",

            "category":

                "Document Tampering",

            "severity":

                "Critical",

            "confidence":

                98

        }

    ]

    from pprint import pprint

    pprint(

        perform_reasoning(sample)

    )

